# Explore LLC

In [1]:
# import
import numpy as np
import os

import xarray as xr
#import h5py 
#import iris

import xmitgcm.llcreader as llcreader
import xmitgcm
import fsspec

import datetime

In [2]:
xmitgcm.__version__, fsspec.__version__

('0.5.0+1.g29f2bd1', '2021.07.0')

# Initialize model object

In [3]:
model = llcreader.ECCOPortalLLC4320Model()
model

# Xarray dataset

In [31]:
ds_sst = model.get_dataset(varnames=['Theta'], k_levels=[0], type='latlon', iter_step=1728)#, iter_step=960)  # Every 12 hours
ds_sst

<xarray.Dataset>
Dimensions:  (face: 13, i: 17280, i_g: 17280, j: 12960, j_g: 12960, k: 1, k_l: 1, k_p1: 2, k_u: 1, time: 860)
Coordinates:
  * k_u      (k_u) int64 0
  * i_g      (i_g) int64 0 1 2 3 4 5 6 ... 17274 17275 17276 17277 17278 17279
  * k_p1     (k_p1) int64 0 1
  * time     (time) datetime64[ns] 2011-09-13 ... 2012-11-15T12:00:00
  * k        (k) int64 0
  * k_l      (k_l) int64 0
  * j_g      (j_g) int64 0 1 2 3 4 5 6 ... 12954 12955 12956 12957 12958 12959
  * face     (face) int64 0 1 2 3 4 5 6 7 8 9 10 11 12
  * j        (j) int64 0 1 2 3 4 5 6 ... 12954 12955 12956 12957 12958 12959
  * i        (i) int64 0 1 2 3 4 5 6 ... 17274 17275 17276 17277 17278 17279
    CS       (j, i) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    SN       (j, i) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    Depth    (j, i) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    drC      (k_p1) >f4 dask.array<chunksize=(2,), meta=np.ndarray>
    drF      (k) >f4 dask.array<chunksize=(1,), meta=np.ndarray>
    dxC      (j, i_g) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    dxF      (j, i) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    dxG      (j_g, i) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    dyC      (j_g, i) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    dyF      (j, i) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    dyG      (j, i_g) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    hFacC    (k, j, i) float32 dask.array<chunksize=(1, 12960, 4320), meta=np.ndarray>
    hFacS    (k, j_g, i) float32 dask.array<chunksize=(1, 12960, 4320), meta=np.ndarray>
    hFacW    (k, j, i_g) float32 dask.array<chunksize=(1, 12960, 4320), meta=np.ndarray>
    PHrefC   (k) >f4 dask.array<chunksize=(1,), meta=np.ndarray>
    PHrefF   (k_p1) >f4 dask.array<chunksize=(2,), meta=np.ndarray>
    rA       (j, i) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    rAs      (j_g, i) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    rAw      (j, i_g) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    Z        (k) >f4 dask.array<chunksize=(1,), meta=np.ndarray>
    Zp1      (k_p1) >f4 dask.array<chunksize=(2,), meta=np.ndarray>
    rhoRef   (k) >f4 dask.array<chunksize=(1,), meta=np.ndarray>
    XC       (j, i) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    YC       (j, i) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    rAz      (j_g, i_g) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    XG       (j_g, i_g) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    YG       (j_g, i_g) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    dxV      (j_g, i_g) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    dyU      (j_g, i_g) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    Zl       (k_l) >f4 dask.array<chunksize=(1,), meta=np.ndarray>
    Zu       (k_u) >f4 dask.array<chunksize=(1,), meta=np.ndarray>
Data variables:
    Theta    (time, k, j, i) float32 dask.array<chunksize=(1, 1, 12960, 4320), meta=np.ndarray>

In [64]:
1728/12

144.0

In [33]:
ds_sst.nbytes / 1e12

0.790091857312

# Grab times

In [32]:
ds_sst.time

<xarray.DataArray 'time' (time: 860)>
array(['2011-09-13T00:00:00.000000000', '2011-09-13T12:00:00.000000000',
       '2011-09-14T00:00:00.000000000', ..., '2012-11-14T12:00:00.000000000',
       '2012-11-15T00:00:00.000000000', '2012-11-15T12:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2011-09-13 ... 2012-11-15T12:00:00

In [34]:
ds_sst.time[0]

<xarray.DataArray 'time' ()>
array('2011-09-13T00:00:00.000000000', dtype='datetime64[ns]')
Coordinates:
    time     datetime64[ns] 2011-09-13

In [35]:
ds_sst.time[0:3].values

array(['2011-09-13T00:00:00.000000000', '2011-09-13T12:00:00.000000000',
       '2011-09-14T00:00:00.000000000'], dtype='datetime64[ns]')

# Grab one time instance

In [41]:
SST_0 = ds_sst.Theta.isel(time=0, k=0)#, i=slice(1000,2000), j=slice(1000,2000))
SST_0

<xarray.DataArray 'Theta' (j: 12960, i: 17280)>
dask.array<getitem, shape=(12960, 17280), dtype=float32, chunksize=(12960, 4320), chunktype=numpy.ndarray>
Coordinates:
    time     datetime64[ns] 2011-09-13
    k        int64 0
  * j        (j) int64 0 1 2 3 4 5 6 ... 12954 12955 12956 12957 12958 12959
  * i        (i) int64 0 1 2 3 4 5 6 ... 17274 17275 17276 17277 17278 17279
    CS       (j, i) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    SN       (j, i) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    Depth    (j, i) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    drF      float32 dask.array<chunksize=(), meta=np.ndarray>
    dxF      (j, i) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    dyF      (j, i) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    hFacC    (j, i) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    PHrefC   float32 dask.array<chunksize=(), meta=np.ndarray>
    rA       (j, i) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    Z        float32 dask.array<chunksize=(), meta=np.ndarray>
    rhoRef   float32 dask.array<chunksize=(), meta=np.ndarray>
    XC       (j, i) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    YC       (j, i) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
Attributes:
    standard_name:  THETA
    long_name:      Potential Temperature
    units:          degC

In [60]:
SST_0.variable

<xarray.Variable (j: 12960, i: 17280)>
dask.array<getitem, shape=(12960, 17280), dtype=float32, chunksize=(12960, 4320), chunktype=numpy.ndarray>
Attributes:
    standard_name:  THETA
    long_name:      Potential Temperature
    units:          degC

In [42]:
SST_values = SST_0.values

In [43]:
SST_values

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=float32)

In [38]:
list(SST_0.coords.keys())

['time',
 'k',
 'j',
 'i',
 'CS',
 'SN',
 'Depth',
 'drF',
 'dxF',
 'dyF',
 'hFacC',
 'PHrefC',
 'rA',
 'Z',
 'rhoRef',
 'XC',
 'YC']

In [57]:
val = SST_values
min1, max1 = np.min(val[np.invert(np.isnan(val))]), np.max(val[np.invert(np.isnan(val))])
min1, max1

(-2.862177, 34.23702)

## Strip coords

In [45]:
drop_coord = []
for key in SST_0.coords.keys():
    if key in ['i','j']:
        continue
    drop_coord.append(key)
drop_coord

['time',
 'k',
 'CS',
 'SN',
 'Depth',
 'drF',
 'dxF',
 'dyF',
 'hFacC',
 'PHrefC',
 'rA',
 'Z',
 'rhoRef',
 'XC',
 'YC']

In [46]:
strip_0 = SST_0.drop_vars(drop_coord)
strip_0

<xarray.DataArray 'Theta' (j: 12960, i: 17280)>
dask.array<getitem, shape=(12960, 17280), dtype=float32, chunksize=(12960, 4320), chunktype=numpy.ndarray>
Coordinates:
  * j        (j) int64 0 1 2 3 4 5 6 ... 12954 12955 12956 12957 12958 12959
  * i        (i) int64 0 1 2 3 4 5 6 ... 17274 17275 17276 17277 17278 17279
Attributes:
    standard_name:  THETA
    long_name:      Potential Temperature
    units:          degC

In [47]:
xr_0 = strip_0.to_dataset()
xr_0

<xarray.Dataset>
Dimensions:  (i: 17280, j: 12960)
Coordinates:
  * j        (j) int64 0 1 2 3 4 5 6 ... 12954 12955 12956 12957 12958 12959
  * i        (i) int64 0 1 2 3 4 5 6 ... 17274 17275 17276 17277 17278 17279
Data variables:
    Theta    (j, i) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>

In [63]:
list(xr_0.data_vars.keys())

['Theta']

# Write to disk

In [48]:
encoding = {'Theta': {'dtype': 'int16', 'scale_factor': 1e-3, 'add_offset': 10., 'zlib': True, 'missing_value': -32768}}

In [49]:
xr_0.to_netcdf('tst.nc', encoding=encoding)

# Read

In [52]:
tst0 = xr.open_dataset('tst.nc',         engine='h5netcdf',
        mask_and_scale=True)

In [53]:
tst0

<xarray.Dataset>
Dimensions:  (i: 17280, j: 12960)
Coordinates:
  * j        (j) int64 0 1 2 3 4 5 6 ... 12954 12955 12956 12957 12958 12959
  * i        (i) int64 0 1 2 3 4 5 6 ... 17274 17275 17276 17277 17278 17279
Data variables:
    Theta    (j, i) float32 ...

In [54]:
SST_tst = tst0.Theta

In [55]:
SST_tst.values

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=float32)

In [56]:
np.min(SST_tst.values[np.invert(np.isnan(SST_tst.values))]), np.max(SST_tst.values[np.invert(np.isnan(SST_tst.values))])

(-2.8620005, 34.237)

In [58]:
min1, max1

(-2.862177, 34.23702)

----

# I/O

## Load a sample file

In [3]:
dpath = '/home/xavier/Oceanography/data/LLC/ThetaUVSalt'
ifile = os.path.join(dpath, 'LLC4320_2012-11-11T12_00_00.nc')

In [4]:
ds_ex = xr.load_dataset(ifile)

In [5]:
ds_ex

<xarray.Dataset>
Dimensions:  (i: 17280, i_g: 17280, j: 12960, j_g: 12960, k_l: 1)
Coordinates:
  * i        (i) int64 0 1 2 3 4 5 6 ... 17274 17275 17276 17277 17278 17279
  * i_g      (i_g) int64 0 1 2 3 4 5 6 ... 17274 17275 17276 17277 17278 17279
  * j        (j) int64 0 1 2 3 4 5 6 ... 12954 12955 12956 12957 12958 12959
  * j_g      (j_g) int64 0 1 2 3 4 5 6 ... 12954 12955 12956 12957 12958 12959
Dimensions without coordinates: k_l
Data variables:
    Theta    (j, i) float32 nan nan nan nan nan nan ... nan nan nan nan nan nan
    U        (j, i_g) float32 nan nan nan nan nan nan ... nan nan nan nan nan
    V        (j_g, i) float32 nan nan nan nan nan nan ... nan nan nan nan nan
    W        (k_l, j, i) float32 nan nan nan nan nan nan ... nan nan nan nan nan
    Salt     (j, i) float32 nan nan nan nan nan nan ... nan nan nan nan nan nan

In [6]:
sst = ds_ex.Theta
sst

<xarray.DataArray 'Theta' (j: 12960, i: 17280)>
array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=float32)
Coordinates:
  * i        (i) int64 0 1 2 3 4 5 6 ... 17274 17275 17276 17277 17278 17279
  * j        (j) int64 0 1 2 3 4 5 6 ... 12954 12955 12956 12957 12958 12959
Attributes:
    standard_name:  THETA
    long_name:      Potential Temperature
    units:          degC

In [10]:
sst_val = sst.values
gd_val = np.isfinite(sst_val)
np.sum(gd_val)

127079722

In [13]:
sst_val[gd_val].min(), sst_val[gd_val].max()

(-3.1070004, 32.919)

----

# All Variables

In [4]:
ds = model.get_dataset(k_levels=[0], type='latlon', iter_step=1728)#, iter_step=960)  # Every 12 hours


In [5]:
ds

<xarray.Dataset>
Dimensions:   (face: 13, i: 17280, i_g: 17280, j: 12960, j_g: 12960, k: 1, k_l: 1, k_p1: 2, k_u: 1, time: 860)
Coordinates: (12/41)
  * face      (face) int64 0 1 2 3 4 5 6 7 8 9 10 11 12
  * i         (i) int64 0 1 2 3 4 5 6 ... 17274 17275 17276 17277 17278 17279
  * i_g       (i_g) int64 0 1 2 3 4 5 6 ... 17274 17275 17276 17277 17278 17279
  * j         (j) int64 0 1 2 3 4 5 6 ... 12954 12955 12956 12957 12958 12959
  * j_g       (j_g) int64 0 1 2 3 4 5 6 ... 12954 12955 12956 12957 12958 12959
  * k         (k) int64 0
    ...        ...
    XG        (j_g, i_g) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    YG        (j_g, i_g) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    dxV       (j_g, i_g) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    dyU       (j_g, i_g) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    Zl        (k_l) >f4 dask.array<chunksize=(1,), meta=np.ndarray>
    Zu        (k_u) >f4 dask.array<chunksize=(1,), meta=np.ndarray>
Data variables: (12/20)
    Eta       (time, j, i) float32 dask.array<chunksize=(1, 12960, 4320), meta=np.ndarray>
    KPPhbl    (time, j, i) float32 dask.array<chunksize=(1, 12960, 4320), meta=np.ndarray>
    oceFWflx  (time, j, i) float32 dask.array<chunksize=(1, 12960, 4320), meta=np.ndarray>
    oceQnet   (time, j, i) float32 dask.array<chunksize=(1, 12960, 4320), meta=np.ndarray>
    oceQsw    (time, j, i) float32 dask.array<chunksize=(1, 12960, 4320), meta=np.ndarray>
    oceSflux  (time, j, i) float32 dask.array<chunksize=(1, 12960, 4320), meta=np.ndarray>
    ...        ...
    SIuice    (time, j, i_g) float32 dask.array<chunksize=(1, 12960, 4320), meta=np.ndarray>
    SIvice    (time, j_g, i) float32 dask.array<chunksize=(1, 1, 4320), meta=np.ndarray>
    Theta     (time, k, j, i) float32 dask.array<chunksize=(1, 1, 12960, 4320), meta=np.ndarray>
    U         (time, k, j, i_g) float32 dask.array<chunksize=(1, 1, 12960, 4320), meta=np.ndarray>
    V         (time, k, j_g, i) float32 dask.array<chunksize=(1, 1, 1, 4320), meta=np.ndarray>
    W         (time, k_l, j, i) float32 dask.array<chunksize=(1, 1, 12960, 4320), meta=np.ndarray>

In [6]:
ds.Eta

<xarray.DataArray 'Eta' (time: 860, j: 12960, i: 17280)>
dask.array<concatenate, shape=(860, 12960, 17280), dtype=float32, chunksize=(1, 12960, 4320), chunktype=numpy.ndarray>
Coordinates:
  * i        (i) int64 0 1 2 3 4 5 6 ... 17274 17275 17276 17277 17278 17279
  * j        (j) int64 0 1 2 3 4 5 6 ... 12954 12955 12956 12957 12958 12959
  * time     (time) datetime64[ns] 2011-09-13 ... 2012-11-15T12:00:00
    CS       (j, i) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    SN       (j, i) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    Depth    (j, i) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    dxF      (j, i) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    dyF      (j, i) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    rA       (j, i) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    XC       (j, i) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
    YC       (j, i) float32 dask.array<chunksize=(12960, 4320), meta=np.ndarray>
Attributes:
    standard_name:  ETAN
    long_name:      Surface Height Anomaly
    units:          m